# Generated by Django 4.0 on 2022-10-20 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_profile_facebook_alter_profile_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='thumbnail',
            field=models.ImageField(default='images/thumbnail.png', upload_to='profiles/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='images/default.png', upload_to='profiles/%Y/%m/%d/'),
        ),
    ]
