# Generated by Django 4.0 on 2022-10-20 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_profile_thumbnail_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='thumbnail',
            field=models.ImageField(default='media/images/thumbnail.png', upload_to='profiles/%Y/%m/%d/'),
        ),
    ]
