# Generated by Django 4.0 on 2022-10-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_profile_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='thumbnail',
            field=models.ImageField(default='/images/thumbnail.png', upload_to='profiles/%Y/%m/%d/'),
        ),
    ]
