# Generated by Django 3.2.16 on 2022-11-19 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0003_reply'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
